apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: huvck87l3-python 
  janus-idp.io/tekton: huvck87l3-python
  backstage.io/kubernetes-id: huvck87l3-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: huvck87l3-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml